// employeesTableConfig.jsx

// key = actual database field name
// label = UI name
// getValue = data name
// editor = data type
// options = for option input
// editable = boolean

export const employeesTableConfig = ({
  managers,
  profiles,
  departments,
  nationalities,
  identificationTypes,
  employmentTypes,
  terminationReasons,
  employmentStatuses,
}) => [
  {
    key: "id",
    label: "ID",
    getValue: (employee) => employee.id,
    editable: false,
    editor: "text",
    show: false,
  },
  // SYSTEM SETTINGS
  {
    key: "profile_id",
    label: "Profile",
    getValue: (employee) => employee.profile_id,
    editable: true,
    editor: "select",
    options: profiles.map((p) => ({
      label: p.email,
      value: p.id,
    })),
    section: "System Settings",
  },

  // PERSONAL INFORMATION
  {
    key: "full_name",
    label: "Full Name",
    getValue: (employee) => employee.full_name,
    editable: true,
    editor: "text",
    required: true,
    section: "Personal Information",
  },
  {
    key: "preferred_name",
    label: "Preferred Name",
    getValue: (employee) => employee.preferred_name,
    editable: true,
    editor: "text",
    section: "Personal Information",
  },
  {
    key: "date_of_birth",
    label: "Date of Birth",
    getValue: (employee) => employee.date_of_birth,
    editable: true,
    editor: "date",
    section: "Personal Information",
    half: true,
  },
  {
    key: "gender",
    label: "Gender",
    getValue: (employee) => employee.gender,
    editable: true,
    editor: "select",
    options: [
      {
        label: "Male",
        value: "Male",
      },
      {
        label: "Female",
        value: "Female",
      },
      { label: "Not Specified", value: "Not Specified" },
    ],
    isSearchable: false,
    section: "Personal Information",
    half: true,
  },
  {
    key: "nationality_id",
    label: "Nationality",
    getValue: (employee) => employee.nationality?.id,
    displayValue: (employee) => employee.nationality?.name,
    editable: true,
    editor: "select",
    options: nationalities.map((n) => ({
      label: n.name,
      value: n.id,
    })),
    section: "Personal Information",
  },
  {
    key: "identification_type_id",
    label: "Identification Type",
    getValue: (employee) => employee.identification_type?.id,
    displayValue: (employee) => employee.identification_type?.name,
    editable: true,
    editor: "select",
    options: identificationTypes.map((i) => ({
      label: i.name,
      value: i.id,
    })),
    isSearchable: false,
    section: "Personal Information",
    half: true,
  },
  {
    key: "identification_number",
    label: "Identification Number",
    getValue: (employee) => employee.identification_number,
    editable: true,
    editor: "text",
    section: "Personal Information",
    half: true,
  },
  {
    key: "marital_status",
    label: "Marital Status",
    getValue: (employee) => employee.marital_status,
    editable: true,
    editor: "select",
    options: [
      { label: "Single", value: "Single" },
      {
        label: "Married (Spouse Not Working)",
        value: "Married (Spouse Not Working)",
      },
      {
        label: "Married (Spouse Working)",
        value: "Married (Spouse Working)",
      },
      {
        label: "Divorced",
        value: "Divorced",
      },
      {
        label: "Widowed",
        value: "Widowed",
      },
    ],
    isSearchable: false,
    section: "Personal Information",
  },

  // CONTACT INFORMATION
  {
    key: "email_personal",
    label: "Email (Personal)",
    getValue: (employee) => employee.email_personal,
    editable: true,
    editor: "text",
    section: "Contact Information",
    half: true,
  },
  {
    key: "email_work",
    label: "Email (Work)",
    getValue: (employee) => employee.email_work,
    editable: true,
    editor: "text",
    section: "Contact Information",
    half: true,
  },
  {
    key: "phone_personal",
    label: "Phone (Personal)",
    getValue: (employee) => employee.phone_personal,
    editable: true,
    editor: "number",
    section: "Contact Information",
    half: true,
  },
  {
    key: "phone_work",
    label: "Phone (Work)",
    getValue: (employee) => employee.phone_work,
    editable: true,
    editor: "number",
    section: "Contact Information",
    half: true,
  },
  {
    key: "emergency_contact_name",
    label: "Emergency Contact Name",
    getValue: (employee) => employee.emergency_contact_name,
    editable: true,
    editor: "text",
    section: "Contact Information",
  },
  {
    key: "emergency_contact_relationship",
    label: "Emergency Contact Relationship",
    getValue: (employee) => employee.emergency_contact_relationship,
    editable: true,
    editor: "select",
    options: [
      {
        label: "Parent",
        value: "Parent",
      },
      {
        label: "Spouse",
        value: "Spouse",
      },
      { label: "Sibling", value: "Sibling" },
      { label: "Child", value: "Child" },
      { label: "Friend", value: "Friend" },
      { label: "Other", value: "Other" },
    ],
    isSearchable: false,
    section: "Contact Information",
  },
  {
    key: "emergency_contact_phone",
    label: "Emergency Contact Phone",
    getValue: (employee) => employee.emergency_contact_phone,
    editable: true,
    editor: "number",
    section: "Contact Information",
  },

  // EMPLOYMENT DETAILS
  {
    key: "employee_id",
    label: "Employee ID",
    getValue: (employee) => employee.employee_id,
    editable: true,
    editor: "text",
    section: "Personal Information",
  },
  {
    key: "department_id",
    label: "Department",
    getValue: (employee) => employee.department?.id,
    displayValue: (employee) => employee.department?.name,
    editable: true,
    editor: "select",
    options: departments.map((d) => ({
      label: d.name,
      value: d.id,
    })),
    section: "Employment Details",
  },
  {
    key: "position",
    label: "Position",
    getValue: (employee) => employee.position,
    editable: true,
    editor: "text",
    section: "Employment Details",
  },
  {
    key: "employment_status_id",
    label: "Employment Status",
    getValue: (employee) => employee.employment_status?.id,
    displayValue: (employee) => employee.employment_status?.name,
    editable: true,
    editor: "select",
    options: employmentStatuses.map((e) => ({
      label: e.name,
      value: e.id,
    })),
    required: true,
    isSearchable: false,
    section: "Employment Details",
    half: true,
  },
  {
    key: "employment_type_id",
    label: "Employment Type",
    getValue: (employee) => employee.employment_type?.id,
    displayValue: (employee) => employee.employment_type?.name,
    editable: true,
    editor: "select",
    options: employmentTypes.map((e) => ({
      label: e.name,
      value: e.id,
    })),
    isSearchable: false,
    section: "Employment Details",
    half: true,
  },
  {
    key: "join_date",
    label: "Join Date",
    getValue: (employee) => employee.join_date,
    editable: true,
    editor: "date",
    section: "Employment Details",
  },
  {
    key: "confirmation_date",
    label: "Confirmation Date",
    getValue: (employee) => employee.confirmation_date,
    editable: true,
    editor: "date",
    section: "Employment Details",
  },
  {
    key: "end_date",
    label: "End Date",
    getValue: (employee) => employee.end_date,
    editable: true,
    editor: "date",
    section: "Employment Details",
  },
  {
    key: "resignation_date",
    label: "Resignation Date",
    getValue: (employee) => employee.resignation_date,
    editable: true,
    editor: "date",
    section: "Employment Details",
  },
  {
    key: "termination_reason_id",
    label: "Termination Reason",
    getValue: (employee) => employee.termination_reason?.id,
    displayValue: (employee) => employee.termination_reason?.name,
    editable: true,
    editor: "select",
    options: terminationReasons.map((t) => ({
      label: t.name,
      value: t.id,
    })),
    isSearchable: false,
    section: "Employment Details",
  },

  // REPORTING MANAGER
  {
    key: "manager_id",
    label: "Manager",
    getValue: (employee) => employee.manager?.id,
    displayValue: (employee) => employee.manager?.full_name,
    editable: true,
    editor: "select",
    options: managers.map((m) => ({
      label: m.full_name,
      value: m.id,
    })),
    section: "Reporting Manager",
  },

  // ADDRESS INFORMATION
  {
    key: "address_work",
    label: "Address (Work)",
    getValue: (employee) => employee.address_work,
    editable: true,
    editor: "text",
    section: "Address Information",
  },
  {
    key: "address_personal",
    label: "Address (Personal)",
    getValue: (employee) => employee.address_personal,
    editable: true,
    editor: "text",
    section: "Address Information",
  },
];
